# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: lmdb.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='lmdb.proto',
  package='MlfLabFea',
  syntax='proto2',
  serialized_pb=_b('\n\nlmdb.proto\x12\tMlfLabFea\"\xb2\x01\n\x07PakData\x12\x0b\n\x03\x66\x65\x61\x18\x01 \x01(\x0c\x12\x0f\n\x07\x66\x65\x61_dim\x18\x02 \x01(\x05\x12\x10\n\x08\x63\x65_label\x18\x03 \x01(\x0c\x12\x0e\n\x06\x63\x65_dim\x18\x04 \x01(\x05\x12\x10\n\x08\x65\x64_label\x18\x05 \x01(\x0c\x12\x0e\n\x06\x65\x64_dim\x18\x06 \x01(\x05\x12\x11\n\tctc_label\x18\x07 \x01(\x0c\x12\x0f\n\x07\x63tc_dim\x18\x08 \x01(\x05\x12\x0e\n\x06mlf_sy\x18\t \x01(\t\x12\x11\n\tmlf_fa_ph\x18\n \x01(\t\":\n\x0eSDTLatticeData\x12\x13\n\x0blattice_num\x18\x01 \x02(\x0c\x12\x13\n\x0blattice_den\x18\x02 \x02(\x0c\"r\n\x14SDTLatticeDataDouble\x12\x13\n\x0blattice_num\x18\x01 \x02(\x0c\x12\x13\n\x0blattice_den\x18\x02 \x02(\x0c\x12\x17\n\x0flattice_num_pgs\x18\x03 \x02(\x0c\x12\x17\n\x0flattice_den_pgs\x18\x04 \x02(\x0c\"\xb8\x02\n\x08\x41SRProto\x12\x0c\n\x04name\x18\x01 \x02(\t\x12\x11\n\tdata_type\x18\x02 \x01(\x05\x12\x0b\n\x03\x64im\x18\x03 \x01(\x05\x12\x0c\n\x04\x64\x61ta\x18\x04 \x01(\x0c\x12\x13\n\x0bstring_data\x18\x05 \x01(\x0c\"\xda\x01\n\x08\x44\x61taType\x12\r\n\tUNDEFINED\x10\x00\x12\t\n\x05\x46LOAT\x10\x01\x12\t\n\x05UINT8\x10\x02\x12\x08\n\x04INT8\x10\x03\x12\n\n\x06UINT16\x10\x04\x12\t\n\x05INT16\x10\x05\x12\t\n\x05INT32\x10\x06\x12\t\n\x05INT64\x10\x07\x12\n\n\x06STRING\x10\x08\x12\x08\n\x04\x42OOL\x10\t\x12\x0b\n\x07\x46LOAT16\x10\n\x12\n\n\x06\x44OUBLE\x10\x0b\x12\n\n\x06UINT32\x10\x0c\x12\n\n\x06UINT64\x10\r\x12\r\n\tCOMPLEX64\x10\x0e\x12\x0e\n\nCOMPLEX128\x10\x0f\x12\x0c\n\x08\x42\x46LOAT16\x10\x10')
)



_ASRPROTO_DATATYPE = _descriptor.EnumDescriptor(
  name='DataType',
  full_name='MlfLabFea.ASRProto.DataType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='UNDEFINED', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='FLOAT', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='UINT8', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='INT8', index=3, number=3,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='UINT16', index=4, number=4,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='INT16', index=5, number=5,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='INT32', index=6, number=6,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='INT64', index=7, number=7,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='STRING', index=8, number=8,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='BOOL', index=9, number=9,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='FLOAT16', index=10, number=10,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DOUBLE', index=11, number=11,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='UINT32', index=12, number=12,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='UINT64', index=13, number=13,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='COMPLEX64', index=14, number=14,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='COMPLEX128', index=15, number=15,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='BFLOAT16', index=16, number=16,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=477,
  serialized_end=695,
)
_sym_db.RegisterEnumDescriptor(_ASRPROTO_DATATYPE)


_PAKDATA = _descriptor.Descriptor(
  name='PakData',
  full_name='MlfLabFea.PakData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='fea', full_name='MlfLabFea.PakData.fea', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='fea_dim', full_name='MlfLabFea.PakData.fea_dim', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ce_label', full_name='MlfLabFea.PakData.ce_label', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ce_dim', full_name='MlfLabFea.PakData.ce_dim', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ed_label', full_name='MlfLabFea.PakData.ed_label', index=4,
      number=5, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ed_dim', full_name='MlfLabFea.PakData.ed_dim', index=5,
      number=6, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ctc_label', full_name='MlfLabFea.PakData.ctc_label', index=6,
      number=7, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ctc_dim', full_name='MlfLabFea.PakData.ctc_dim', index=7,
      number=8, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='mlf_sy', full_name='MlfLabFea.PakData.mlf_sy', index=8,
      number=9, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='mlf_fa_ph', full_name='MlfLabFea.PakData.mlf_fa_ph', index=9,
      number=10, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=26,
  serialized_end=204,
)


_SDTLATTICEDATA = _descriptor.Descriptor(
  name='SDTLatticeData',
  full_name='MlfLabFea.SDTLatticeData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='lattice_num', full_name='MlfLabFea.SDTLatticeData.lattice_num', index=0,
      number=1, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='lattice_den', full_name='MlfLabFea.SDTLatticeData.lattice_den', index=1,
      number=2, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=206,
  serialized_end=264,
)


_SDTLATTICEDATADOUBLE = _descriptor.Descriptor(
  name='SDTLatticeDataDouble',
  full_name='MlfLabFea.SDTLatticeDataDouble',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='lattice_num', full_name='MlfLabFea.SDTLatticeDataDouble.lattice_num', index=0,
      number=1, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='lattice_den', full_name='MlfLabFea.SDTLatticeDataDouble.lattice_den', index=1,
      number=2, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='lattice_num_pgs', full_name='MlfLabFea.SDTLatticeDataDouble.lattice_num_pgs', index=2,
      number=3, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='lattice_den_pgs', full_name='MlfLabFea.SDTLatticeDataDouble.lattice_den_pgs', index=3,
      number=4, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=266,
  serialized_end=380,
)


_ASRPROTO = _descriptor.Descriptor(
  name='ASRProto',
  full_name='MlfLabFea.ASRProto',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='MlfLabFea.ASRProto.name', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='data_type', full_name='MlfLabFea.ASRProto.data_type', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='dim', full_name='MlfLabFea.ASRProto.dim', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='data', full_name='MlfLabFea.ASRProto.data', index=3,
      number=4, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='string_data', full_name='MlfLabFea.ASRProto.string_data', index=4,
      number=5, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _ASRPROTO_DATATYPE,
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=383,
  serialized_end=695,
)

_ASRPROTO_DATATYPE.containing_type = _ASRPROTO
DESCRIPTOR.message_types_by_name['PakData'] = _PAKDATA
DESCRIPTOR.message_types_by_name['SDTLatticeData'] = _SDTLATTICEDATA
DESCRIPTOR.message_types_by_name['SDTLatticeDataDouble'] = _SDTLATTICEDATADOUBLE
DESCRIPTOR.message_types_by_name['ASRProto'] = _ASRPROTO
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

PakData = _reflection.GeneratedProtocolMessageType('PakData', (_message.Message,), dict(
  DESCRIPTOR = _PAKDATA,
  __module__ = 'lmdb_pb2'
  # @@protoc_insertion_point(class_scope:MlfLabFea.PakData)
  ))
_sym_db.RegisterMessage(PakData)

SDTLatticeData = _reflection.GeneratedProtocolMessageType('SDTLatticeData', (_message.Message,), dict(
  DESCRIPTOR = _SDTLATTICEDATA,
  __module__ = 'lmdb_pb2'
  # @@protoc_insertion_point(class_scope:MlfLabFea.SDTLatticeData)
  ))
_sym_db.RegisterMessage(SDTLatticeData)

SDTLatticeDataDouble = _reflection.GeneratedProtocolMessageType('SDTLatticeDataDouble', (_message.Message,), dict(
  DESCRIPTOR = _SDTLATTICEDATADOUBLE,
  __module__ = 'lmdb_pb2'
  # @@protoc_insertion_point(class_scope:MlfLabFea.SDTLatticeDataDouble)
  ))
_sym_db.RegisterMessage(SDTLatticeDataDouble)

ASRProto = _reflection.GeneratedProtocolMessageType('ASRProto', (_message.Message,), dict(
  DESCRIPTOR = _ASRPROTO,
  __module__ = 'lmdb_pb2'
  # @@protoc_insertion_point(class_scope:MlfLabFea.ASRProto)
  ))
_sym_db.RegisterMessage(ASRProto)


# @@protoc_insertion_point(module_scope)
